name: 'Upload Things to Supabase Storage'
description:
  'Upload your stuff to supabase storage. It supports self hosted supabase.'
author: 'xiaohai-huang'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'green'

# Define your inputs here.
inputs:
  SUPABASE_PUBLIC_URL:
    description: 'Supabase Public URL.'
    required: true
  SUPABASE_KEY:
    description: 'Supabase service role key.'
    required: true
  BUCKET:
    description: 'The bucket id to operate on.'
    required: true
  SOURCE_DIR:
    description: 'Source directory.'
    required: true
  TARGET_DIR:
    description: 'The directory on bukect.'
    required: true

runs:
  using: node20
  main: dist/index.js
